config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # ログインしていないユーザーのルートパス
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  # ログイン済みユーザーのルートパス
  authenticated :user do
    root 'main_menu#index', as: :authenticated_root
  end

  resources :patients do
    resources :conditions, only: [:new, :create]
    collection do
      get 'search'
    end
    member do
      post 'select'
    end
  end
  
  resources :conditions, only: [:index, :edit, :update, :destroy]

  get 'main_menu', to: 'main_menu#index', as: :main_menu
  get 'settings', to: 'settings#index'
  get 'patients/search', to: 'patients#search'

  # Active Storageのルーティング（変更なし）
  get '/rails/active_storage/blobs/proxy/:signed_id/*filename', to: 'active_storage/blobs/proxy#show'
  get '/rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/proxy#show'
  get '/rails/active_storage/blobs/redirect/:signed_id/*filename', to: 'active_storage/blobs/redirect#show'
  get '/rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename', to: 'active_storage/representations/redirect#show'
  get '/rails/active_storage/disk/:encoded_key/*filename', to: 'active_storage/disk#show'
  put '/rails/active_storage/disk/:encoded_token', to: 'active_storage/disk#update'
  post '/rails/active_storage/direct_uploads', to: 'active_storage/direct_uploads#create'

 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>体調番長</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'patients', "data-turbo-track": "reload" if controller_name == 'patients' %>
  <%= stylesheet_link_tag 'conditions', "data-turbo-track": "reload" if controller_name == 'conditions' %>
  
 <%# 以下の行を削除または無効化 %>
<%#= javascript_importmap_tags %>
<%#= javascript_include_tag "application", "data-turbo-track": "reload" %>
  
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
  <nav>
  <div class="title">体調番長</div>
  <% if user_signed_in? %>
    <div class="user-info"><%= current_user.name %>さんがログイン中です</div>
  <% end %>
  <ul>
    <li><%= link_to image_tag('ho-mubotann.png', alt: 'ホームアイコン', class: 'nav-icon'), main_menu_path %></li>
    <li><%= link_to image_tag('yu-za-.png', alt: '患者一覧アイコン', class: 'nav-icon'), patients_path %></li>
    <li><%= link_to image_tag('settei.png', alt: '設定アイコン', class: 'nav-icon'), settings_path %></li>
    <li><%= link_to image_tag('kautte.png', alt: '体調管理一覧アイコン', class: 'nav-icon'), conditions_path %></li>
  </ul>
</nav>

  <%= yield %>

  <footer>
    <p>by haru-teck</p>
  </footer>
</body>
</html>